### ISSUE TITLE
Wrong sum of transactions

### ISSUE THREAD

**Issue by twkrol** [cbytensky/katnip#3]
I made a transfer of 580K KAS to an empty wallet, I can see the list of all incoming KAS, but the total is wrong: it shows 560K. Probably the first transaction (20K) was not counted.
![obraz](https://user-images.githubusercontent.com/377245/149905772-e820aab3-ae97-45b1-a4bc-5ccfbdc3e1be.png)

**Comment by cbytensky** [comment]
I need full address to investigate.
